# Generated by Django 6.1 on 2026-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openoutreach_config', '0002_rename_operator_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
